---
- hosts: linux
  user: root
  gather_facts: True

  vars:
    motd_centos: Welcome to CentOS Linux - Ansible Rocks (3)
    motd_ubuntu: Welcome to Ubuntu Linux - Ansible Rocks (3)

  tasks:
    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd_centos }}"
        dest: /etc/motd
      notify: MOTD changed
      when: ansible_distribution == "CentOS"

    - name: Configure a MOTD (message of the day)
      copy:
        content: "{{ motd_ubuntu }}"
        dest: /etc/motd
      notify: MOTD changed
      when: ansible_distribution == "Ubuntu"

  # Handlers: the list of handlers that are executed as a notify key from a task
  handlers:
    - name: MOTD changed
      debug:
        msg: The MOTD changed

...