---
  - name: Configure Webserver with nginx
    hosts: devserver
    become: yes

    tasks: 
      - name: Install nginx
        apt: 
          name: nginx
          state: latest
          #update_cache: yes
          #install_recommends: no
      
      - name: Copy nginx configuration file
        copy:
            dest: /etc/nginx/sites-available/default
            src: files/nginx.conf 
      
      - name: Enable Configuration
        file:
            path: /etc/nginx/sites-available/default
            src: /etc/nginx/sites-available/default
            state: link

      - name: Copy index.html
        template:
            dest: /usr/share/nginx/html/index.html
            src: templates/index.html.j2
            mode: 0644
      
      - name: Restart nginx
        service:
            name: nginx
            state: restarted
        