---
- hosts: localhost
  connection: local
  tasks:
    - name: deploy nginx docker container
      docker_container:
         image: nginx:latest
         name: nginx
         state: started
         auto_remove: true
         ports:
           - "8090:80"